#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.2
#  in conjunction with Tcl version 8.6
#    Mar 10, 2020 05:55:46 PM -05  platform: Linux
#    Mar 10, 2020 05:58:31 PM -05  platform: Linux
#    Mar 19, 2020 09:07:54 PM -05  platform: Linux
#    Mar 19, 2020 10:01:57 PM -05  platform: Linux

import sys

from logic import *

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def modelWord():
    sword = w.Text1.get("1.0", tk.END).strip()
    if (sword!=""):
        w.Text2.delete("1.0", tk.END) 
        w.Text2.insert(tk.END, modelCadena(sword))   
    sys.stdout.flush()
#WeAppreciateThePower Baby plug in upload your mind http://ow.ly

def modelUser():    
    sword = w.Text1.get("1.0", tk.END).strip()
    if (sword!=""):
        w.Text2.delete("1.0", tk.END) 
        w.Text2.insert(tk.END, modelUsuario(sword))   
    sys.stdout.flush()

def modelWord():    
    sword = w.Text1.get("1.0", tk.END).strip()
    if (sword!=""):
        w.Text2.delete("1.0", tk.END) 
        w.Text2.insert(tk.END, modelCadena(sword))   
    sys.stdout.flush()

def modelUser():    
    sword = w.Text1.get("1.0", tk.END).strip()
    if (sword!=""):
        w.Text2.delete("1.0", tk.END) 
        w.Text2.insert(tk.END, modelUsuario(sword))   
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import sentence
    sentence.vp_start_gui()





