#############################################################################
# Generated by PAGE version 5.0.2
#  in conjunction with Tcl version 8.6
#  Mar 19, 2020 10:01:47 PM -05  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background #5b2dd8 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 853x535+212+131
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Sentence Piece UV"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -background #00ACEE -cursor fleur -height 590 \
        -highlightcolor black -width 907 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab51 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background #2b54d8 \
        -font {-family {Courier New} -size 10 -weight bold} \
        -foreground #ffffff -highlightcolor black \
        -text {ENTER THE TEXT YOU WANT TO TOKENIZE} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex52 \
        -background white -font {-family {Courier New} -size 10} \
        -foreground black -height 235 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 324 -wrap word 
    $site_3_0.tex52 configure -font "-family {Courier New} -size 10"
    $site_3_0.tex52 insert end text
    vTcl:DefineAlias "$site_3_0.tex52" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but53 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -command event \
        -font {-family {Courier New} -size 10 -weight bold} \
        -foreground #0c0c0c -highlightcolor black -text {Model word} 
    vTcl:DefineAlias "$site_3_0.but53" "Model_word" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but54 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Courier New} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Model user} 
    vTcl:DefineAlias "$site_3_0.but54" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe55 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe55" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex56 \
        -background white -font {-family {Courier New} -size 10} \
        -foreground black -height 394 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 283 -wrap word 
    $site_3_0.tex56 configure -font "-family {Courier New} -size 10"
    $site_3_0.tex56 insert end text
    vTcl:DefineAlias "$site_3_0.tex56" "Text2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background #2b54d8 \
        -font {-family {Courier New} -size 10 -weight bold} \
        -foreground #ffffff -highlightcolor black -text OUTPUT 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Courier New} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Suggest list of emojis} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis47 \
        -background white -font {-family {Courier New} -size 10} \
        -foreground $vTcl(actual_gui_fg) -height 115 -width 260 
    $site_3_0.lis47 configure -font "-family {Courier New} -size 10"
    $site_3_0.lis47 insert end text
    vTcl:DefineAlias "$site_3_0.lis47" "Listunicode" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.051 -width 0 \
        -relwidth 0.516 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex52 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.153 -width 0 \
        -relwidth 0.357 -height 0 -relheight 0.398 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.451 -y 0 -rely 0.203 -height 0 \
        -relheight 0.108 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.451 -y 0 -rely 0.356 -width 108 \
        -relwidth 0 -height 59 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe55 \
        -in $site_3_0 -x 0 -relx 0.611 -y 0 -rely 0.017 -height 0 \
        -relheight 0.976 -anchor nw -bordermode inside 
    place $site_3_0.tex56 \
        -in $site_3_0 -x 0 -relx 0.635 -y 0 -rely 0.204 -width 0 \
        -relwidth 0.311 -height 0 -relheight 0.669 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.71 -y 0 -rely 0.051 -width 0 \
        -relwidth 0.141 -height 0 -relheight 0.09 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.576 -width 0 \
        -relwidth 0.535 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis47 \
        -in $site_3_0 -x 0 -relx 0.181 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.295 -height 0 -relheight 0.213 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra46
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.034 -height 0 \
        -relheight 1.009 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

