#############################################################################
# Generated by PAGE version 5.0.2
#  in conjunction with Tcl version 8.6
#  Mar 10, 2020 05:56:59 PM -05  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background #5b2dd8 
    wm focusmodel $top passive
    wm geometry $top 556x285+331+137
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Sentence Piece UV"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    vTcl:copy_lock $top
    frame $top.fra46 \
        -borderwidth 2 -background #2f04d8 -cursor fleur -height 455 \
        -width 605 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab51 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Courier New} -size 10} \
        -foreground $vTcl(actual_gui_fg) \
        -text {Enter the text you want to tokenize} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex52 \
        -background white -font {-family {Courier New} -size 10} \
        -foreground black -height 174 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 286 -wrap word 
    $site_3_0.tex52 configure -font "-family {Courier New} -size 10"
    $site_3_0.tex52 insert end text
    vTcl:DefineAlias "$site_3_0.tex52" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but53 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -command event \
        -font {-family {Courier New} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Model word} 
    vTcl:DefineAlias "$site_3_0.but53" "Model_word" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but54 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Courier New} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Model user} 
    vTcl:DefineAlias "$site_3_0.but54" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe55 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe55" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex56 \
        -background white -font {-family {Courier New} -size 10} \
        -foreground black -height 164 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 186 -wrap word 
    $site_3_0.tex56 configure -font "-family {Courier New} -size 10"
    $site_3_0.tex56 insert end text
    vTcl:DefineAlias "$site_3_0.tex56" "Text2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #00edc6 -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Courier New} -size 10} \
        -foreground $vTcl(actual_gui_fg) -text Output 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.036 -y 0 -rely 0.035 -width 0 \
        -relwidth 0.516 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex52 \
        -in $site_3_0 -x 0 -relx 0.036 -y 0 -rely 0.174 -width 0 \
        -relwidth 0.511 -height 0 -relheight 0.604 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.036 -y 0 -rely 0.833 -height 0 \
        -relheight 0.108 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.357 -y 0 -rely 0.833 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe55 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.014 -height 0 \
        -relheight 0.979 -anchor nw -bordermode inside 
    place $site_3_0.tex56 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.174 -width 0 \
        -relwidth 0.332 -height 0 -relheight 0.569 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.732 -y 0 -rely 0.035 -width 0 \
        -relwidth 0.141 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.007 -height 0 \
        -relheight 1.011 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

